import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navigation from './components/Navigation';
import './globals.css';
import { ReactQueryProvider } from '@/app/components/providers/ReactQuery';
import { ChakraUIProvider } from '@/app/components/providers/ChakraUI';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'WebMeets',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <ChakraUIProvider>
            <Navigation>{children}</Navigation>
          </ChakraUIProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
